openapi: 3.1.0
info:
  title: kmoniPrettyAPI
  version: '1.0'
  summary: 強震モニターのAPIを機械的に変更し、処理時間の短縮を図ったAPI
servers: []
paths:
  '/v1/info/{time}':
    get:
      summary: Get current eq info
      tags: []
      responses:
        '200':
          $ref: '#/components/responses/eqReport'
        '204':
          description: 揺れのデータが存在しない場合
          headers:
            Cache-Control:
              schema:
                type: string
                default: no-store
                enum:
                  - no-store
                  - public
              description: 基本は`no-store`ですが、時間指定された場合は`public`になります
        '400':
          description: Bad Request
        '404':
          description: 未来の時刻が指定された場合
          headers:
            Cache-Control:
              schema:
                type: string
                default: no-store
                enum:
                  - no-store
                example: no-store
        '429':
          description: 異常な量のリクエストがあった場合
          headers:
            Cache-Control:
              schema:
                type: string
                default: no-store
                enum:
                  - no-store
                example: no-store
        '':
          description: ''
      operationId: get-info
      parameters:
        - schema:
            type: string
          in: header
      description: 現在もしくは指定された時刻の地震情報を取得します。
    parameters:
      - schema:
          type: integer
          example: 1638700273
          minimum: 0
          format: int64
        name: time
        in: path
        description: 取得したい時間 (Unix Time)
components:
  schemas: {}
  responses:
    eqReport:
      description: 揺れ情報
      content:
        application/json:
          schema:
            type: object
            properties:
              time:
                type: integer
                description: データの時刻 (Unixtime)
                format: int64
                example: 1638700273
                minimum: 0
              region:
                type: string
              latitude:
                type: number
                description: 緯度
                format: float
                minimum: -90
                maximum: 90
              longitude:
                type: number
                description: 経度
                format: float
                minimum: -180
                maximum: 180
              depth:
                type: integer
                minimum: 0
                description: 震源の深さ(km)
                format: int32
              japanese_intensity:
                type: integer
                description: 日本の深度
                format: int32
                minimum: 0
                maximum: 9
                example: 3
              magunitude:
                type: number
                description: マグニチュード
                minimum: 0
                format: float
              report_num:
                type: integer
                minimum: 1
              alert_type:
                type: string
              final:
                type: boolean
              origin_time:
                type: integer
                format: int64
                minimum: 0
                example: 1638700273
            required:
              - time
      headers:
        Cache-Control:
          schema:
            type: string
            default: no-store
            enum:
              - no-store
              - public
            example: no-store
          description: 基本は`no-store`ですが、時間指定された場合は`public`になります
  securitySchemes: {}
  parameters: {}
