
name: Deploy OpenAPI docs


on:
  push:
    branches: [ master ]
    paths:
      - kmoniPrettyAPI.yaml
      - .github/workflows/docs-site.yml

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: setup node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'

      - name: Install ReDoc
        run: npm install -g redoc-cli
        
      - name: Build OpenAPI file
        run: |
          redoc-cli bundle ./kmoniPrettyAPI.yaml
          mkdir public
          mv redoc-static.html public/apispec.html
        
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
